package com.rioxy.music;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.database.Cursor;import android.net.Uri;import android.os.*;import android.provider.MediaStore;import android.view.*;import android.widget.*;import androidx.activity.result.ActivityResultLauncher;import androidx.activity.result.contract.ActivityResultContracts;import androidx.appcompat.app.AppCompatActivity;import androidx.media3.common.MediaItem;import androidx.media3.exoplayer.ExoPlayer;import androidx.recyclerview.widget.LinearLayoutManager;import androidx.recyclerview.widget.RecyclerView;import java.util.*;
public class MainActivity extends AppCompatActivity implements SongAdapter.Listener{
 RecyclerView list; EditText search; TextView heading,nowTitle,nowArtist; ImageButton play,prev,next; SongAdapter adapter; List<Song> all=new ArrayList<>(),queue=new ArrayList<>(); Set<Long> favorites=new HashSet<>(); int current=-1; ExoPlayer player; ActivityResultLauncher<String> permission;
 @Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);list=findViewById(R.id.list);search=findViewById(R.id.search);heading=findViewById(R.id.heading);nowTitle=findViewById(R.id.nowTitle);nowArtist=findViewById(R.id.nowArtist);play=findViewById(R.id.play);prev=findViewById(R.id.prev);next=findViewById(R.id.next);adapter=new SongAdapter(this,favorites);list.setLayoutManager(new LinearLayoutManager(this));list.setAdapter(adapter);player=new ExoPlayer.Builder(this).build();
 permission=registerForActivityResult(new ActivityResultContracts.RequestPermission(),ok->{if(ok)loadSongs();else Toast.makeText(this,"Music permission is needed to read songs on your device.",Toast.LENGTH_LONG).show();});
 search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){filter(s.toString());}public void afterTextChanged(android.text.Editable e){}});
 findViewById(R.id.homeTab).setOnClickListener(v->{heading.setText("Your music");filter("");});findViewById(R.id.libraryTab).setOnClickListener(v->{heading.setText("Library");filter("");});findViewById(R.id.favoritesTab).setOnClickListener(v->{heading.setText("Favorites");List<Song>x=new ArrayList<>();for(Song s:all)if(favorites.contains(s.id))x.add(s);adapter.submit(x);});findViewById(R.id.settingsTab).setOnClickListener(v->settings());play.setOnClickListener(v->{if(player.isPlaying()){player.pause();play.setImageResource(android.R.drawable.ic_media_play);}else{player.play();play.setImageResource(android.R.drawable.ic_media_pause);}});prev.setOnClickListener(v->previous());next.setOnClickListener(v->next());
 if(Build.VERSION.SDK_INT>=33)permission.launch(Manifest.permission.READ_MEDIA_AUDIO);else if(checkSelfPermission(Manifest.permission.READ_EXTERNAL_STORAGE)!=PackageManager.PERMISSION_GRANTED)permission.launch(Manifest.permission.READ_EXTERNAL_STORAGE);else loadSongs(); }
 void loadSongs(){all.clear();Cursor c=getContentResolver().query(MediaStore.Audio.Media.EXTERNAL_CONTENT_URI,new String[]{MediaStore.Audio.Media._ID,MediaStore.Audio.Media.TITLE,MediaStore.Audio.Media.ARTIST,MediaStore.Audio.Media.ALBUM},MediaStore.Audio.Media.IS_MUSIC+" != 0",null,MediaStore.Audio.Media.TITLE+" COLLATE NOCASE ASC");if(c!=null){while(c.moveToNext()){long id=c.getLong(0);String t=c.getString(1),a=c.getString(2),al=c.getString(3);Uri u=Uri.withAppendedPath(MediaStore.Audio.Media.EXTERNAL_CONTENT_URI,String.valueOf(id));all.add(new Song(id,t==null?"Unknown":t,a==null?"Unknown artist":a,al==null?"":al,u.toString()));}c.close();}filter("");heading.setText(all.isEmpty()?"No music found":"Your music • "+all.size());}
 void filter(String q){String z=q.toLowerCase(Locale.ROOT);List<Song>x=new ArrayList<>();for(Song s:all)if((s.title+" "+s.artist+" "+s.album).toLowerCase(Locale.ROOT).contains(z))x.add(s);adapter.submit(x);}
 public void play(Song s){int i=all.indexOf(s);current=i;player.setMediaItem(MediaItem.fromUri(Uri.parse(s.uri)));player.prepare();player.play();nowTitle.setText(s.title);nowArtist.setText(s.artist);play.setImageResource(android.R.drawable.ic_media_pause);}
 public void favorite(Song s){if(favorites.contains(s.id))favorites.remove(s.id);else favorites.add(s.id);getPreferences(0).edit().putString("favorites",join()).apply();adapter.notifyDataSetChanged();}
 String join(){StringBuilder b=new StringBuilder();for(Long x:favorites){if(b.length()>0)b.append(',');b.append(x);}return b.toString();}
 void previous(){if(all.isEmpty())return;current=(current-1+all.size())%all.size();play(all.get(current));} void next(){if(all.isEmpty())return;current=(current+1)%all.size();play(all.get(current));}
 void settings(){new AlertDialog.Builder(this).setTitle("RØYX Music").setMessage("Audio quality\n\nRØYX preserves the quality of your source files. Actual output quality also depends on the source, Android audio path and device hardware.\n\nSpotify integration can be added for account/catalog metadata and permitted playback control; Spotify streaming has platform restrictions.").setPositiveButton("OK",null).show();}
 @Override protected void onDestroy(){player.release();super.onDestroy();}
}
